# Generated by Django 5.1.2 on 2024-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet',
            name='user',
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='spreadsheet_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='spreadsheet',
            table='work1_spreadsheet',
        ),
    ]
