# Generated by Django 5.1.2 on 2024-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0002_remove_spreadsheet_user_spreadsheet_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
