# Generated by Django 5.1.2 on 2024-12-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work1', '0003_alter_spreadsheet_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='eBayAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
